language: go
go:
- 1.7.4
- 1.8rc3
notifications:
  slack:
    secure: P/JSFKXE6VcUxGpRnRcQVjkjmOAyTF/3bp+8aQlG0qMxtMCSPD/i4ibOKT41Gbwdm5kCmmy9320tpgBTsdt7sPL7ktB9ta1lrasBtep62NiVS4wfVcqv09YzUVOxnfbxfampzqJJ56KXxcMQ/XeCZatBJUswSmth/Vnr7wOBzvPKTQm+dp9Gl/tWET3FHMRd6fqrN+7QBkZxOQe8UHNmBbIb3GW7NviVVFLkQk9DsxO7aIO9HpyQa+A9XDBH8ij0nWIFqrzXSHBdmDhFLNN4CjIkT4B50q6kPgQf5DRcFg4UUNZFl9+EHro4hbDBKR1nr3Qg4LOR10EoiqwDbHmYFlTvbpHJKGQkNERnwMVxugqKP70D5CoLjaMP0BlWP/Unquxl7B8kE3zTe6UjDEjfpsER8PmYteN0UcsAGWn+1OCKEuNUQdnBjL5Nu7B/yAc6ZkeiyU30VOejBW+6LQfLsfYEImy1+QNgJgJS8k9kp0MwU/16MNteemq7J96re5g9Gsz57AP3ABSyMk984L2dmB2axQaZNw4DRm13A/nmqLZbbj3BdzBFriJVMOaiNyRQlPfzw56zpBtZF2ZoBmxlHZdjVJGJyYFDm7TGzqKAodX2NjOIVhP30yDuqbX9gx0eFlKFoT8RFipB+8vbVD61SyMAebCbhlqjQERytbugdMo=
